.TH "c_files/main.c" 3 "Tue Jun 15 2021" "Version 0.1" "Arborescence_Displayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c_files/main.c \- The main function of our project\&. It is used to run the program and get options given by the user\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/structures\&.h'\fP
.br
\fC#include '\&.\&./include/save\&.h'\fP
.br
\fC#include '\&.\&./include/md5sum\&.h'\fP
.br
\fC#include '\&.\&./include/tree\&.h'\fP
.br
\fC#include '\&.\&./include/scan\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBread_s_directory\fP (\fBs_directory\fP *dir)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
The main function of our project\&. It is used to run the program and get options given by the user\&. 


.PP
\fBAuthor\fP
.RS 4
Blanchot Lukas, Viala Alexandre, Chaillard Léo, Lignon Thomas 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2021-06-12
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2021 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Arborescence_Displayer from the source code\&.
